"""SLMP client library with high-level helpers as the recommended user surface.

The primary user-facing entry points are:

- ``read_typed`` / ``write_typed``
- ``read_words_single_request`` / ``read_dwords_single_request``
- ``read_words_chunked`` / ``read_dwords_chunked``
- ``write_bit_in_word``
- ``read_named`` / ``write_named``
- ``poll``
"""

__version__ = "0.1.11"

from .async_client import AsyncSlmpClient
from .client import SlmpClient
from .constants import Command, FrameType, ModuleIONo, PLCSeries
from .core import (
    DEVICE_CODES,
    BlockReadResult,
    CpuOperationState,
    CpuOperationStatus,
    DeviceBlockResult,
    DeviceRef,
    ExtensionSpec,
    LabelArrayReadPoint,
    LabelArrayReadResult,
    LabelArrayWritePoint,
    LabelRandomReadResult,
    LabelRandomWritePoint,
    LongTimerResult,
    MonitorResult,
    RandomReadResult,
    SlmpResponse,
    SlmpTarget,
    SlmpTraceFrame,
    TypeNameInfo,
    decode_cpu_operation_state,
    parse_device,
    parse_extended_device,
)
from .device_ranges import (
    SlmpDeviceRangeCatalog,
    SlmpDeviceRangeCategory,
    SlmpDeviceRangeEntry,
    SlmpDeviceRangeFamily,
    SlmpDeviceRangeNotation,
    build_device_range_catalog_for_family,
    family_label,
    normalize_device_range_family,
    read_device_range_catalog_for_family,
    read_device_range_catalog_for_family_sync,
)
from .errors import (
    SlmpBoundaryBehaviorWarning,
    SlmpError,
    SlmpPracticalPathWarning,
    SlmpUnsupportedDeviceError,
)
from .utils import (
    QueuedAsyncSlmpClient,
    SlmpConnectionOptions,
    normalize_address,
    open_and_connect,
    open_and_connect_sync,
    poll,
    poll_sync,
    read_bits,
    read_bits_sync,
    read_dwords,
    read_dwords_chunked,
    read_dwords_chunked_sync,
    read_dwords_single_request,
    read_dwords_single_request_sync,
    read_dwords_sync,
    read_named,
    read_named_sync,
    read_typed,
    read_typed_sync,
    read_words,
    read_words_chunked,
    read_words_chunked_sync,
    read_words_single_request,
    read_words_single_request_sync,
    read_words_sync,
    write_bit_in_word,
    write_bit_in_word_sync,
    write_bits,
    write_bits_sync,
    write_dwords_chunked,
    write_dwords_chunked_sync,
    write_dwords_single_request,
    write_dwords_single_request_sync,
    write_named,
    write_named_sync,
    write_typed,
    write_typed_sync,
    write_words_chunked,
    write_words_chunked_sync,
    write_words_single_request,
    write_words_single_request_sync,
)

__all__ = [
    "AsyncSlmpClient",
    "BlockReadResult",
    "Command",
    "CpuOperationState",
    "CpuOperationStatus",
    "DEVICE_CODES",
    "DeviceBlockResult",
    "DeviceRef",
    "ExtensionSpec",
    "FrameType",
    "LabelArrayReadPoint",
    "LabelArrayReadResult",
    "LabelArrayWritePoint",
    "LabelRandomReadResult",
    "LabelRandomWritePoint",
    "LongTimerResult",
    "ModuleIONo",
    "MonitorResult",
    "PLCSeries",
    "QueuedAsyncSlmpClient",
    "SlmpConnectionOptions",
    "RandomReadResult",
    "SlmpClient",
    "SlmpBoundaryBehaviorWarning",
    "SlmpError",
    "SlmpPracticalPathWarning",
    "SlmpUnsupportedDeviceError",
    "SlmpResponse",
    "SlmpTarget",
    "SlmpTraceFrame",
    "TypeNameInfo",
    "decode_cpu_operation_state",
    "SlmpDeviceRangeCatalog",
    "SlmpDeviceRangeCategory",
    "SlmpDeviceRangeEntry",
    "SlmpDeviceRangeFamily",
    "SlmpDeviceRangeNotation",
    "normalize_address",
    "normalize_device_range_family",
    "open_and_connect",
    "open_and_connect_sync",
    "parse_extended_device",
    "parse_device",
    "poll",
    "poll_sync",
    "read_bits",
    "read_bits_sync",
    "read_dwords",
    "read_dwords_chunked",
    "read_dwords_chunked_sync",
    "read_dwords_single_request",
    "read_dwords_single_request_sync",
    "read_dwords_sync",
    "read_named",
    "read_named_sync",
    "read_typed",
    "read_typed_sync",
    "read_device_range_catalog_for_family",
    "read_device_range_catalog_for_family_sync",
    "read_words",
    "read_words_chunked",
    "read_words_chunked_sync",
    "read_words_single_request",
    "read_words_single_request_sync",
    "read_words_sync",
    "write_bit_in_word",
    "write_bit_in_word_sync",
    "write_bits",
    "write_bits_sync",
    "write_dwords_chunked",
    "write_dwords_chunked_sync",
    "write_dwords_single_request",
    "write_dwords_single_request_sync",
    "write_named",
    "write_named_sync",
    "write_typed",
    "write_typed_sync",
    "write_words_chunked",
    "write_words_chunked_sync",
    "write_words_single_request",
    "write_words_single_request_sync",
    "build_device_range_catalog_for_family",
    "family_label",
]
