"""SLMP end-code names and messages."""

from __future__ import annotations

from typing import Literal

SlmpEndCodeLanguage = Literal["en", "ja"]

_END_CODE_NAMES: dict[int, str] = {
    0x1080: 'slmp_end_code_1080',
    0x1120: 'slmp_end_code_1120',
    0x1124: 'slmp_end_code_1124',
    0x1128: 'slmp_end_code_1128',
    0x1129: 'slmp_end_code_1129',
    0x112C: 'slmp_end_code_112c',
    0x112D: 'slmp_end_code_112d',
    0x112E: 'slmp_end_code_112e',
    0x1133: 'slmp_end_code_1133',
    0x1134: 'slmp_end_code_1134',
    0x1152: 'slmp_end_code_1152',
    0x1155: 'slmp_end_code_1155',
    0x1157: 'slmp_end_code_1157',
    0x1158: 'slmp_end_code_1158',
    0x1165: 'slmp_end_code_1165',
    0x1166: 'slmp_end_code_1166',
    0x1167: 'slmp_end_code_1167',
    0x1180: 'slmp_end_code_1180',
    0x1801: 'slmp_end_code_1801',
    0x1811: 'slmp_end_code_1811',
    0x1830: 'slmp_end_code_1830',
    0x1845: 'slmp_end_code_1845',
    0x1F07: 'slmp_end_code_1f07',
    0x20E0: 'slmp_end_code_20e0',
    0x2160: 'slmp_end_code_2160',
    0x2220: 'slmp_end_code_2220',
    0x2221: 'slmp_end_code_2221',
    0x2250: 'slmp_end_code_2250',
    0x24C0: 'slmp_end_code_24c0',
    0x24C1: 'slmp_end_code_24c1',
    0x24C2: 'slmp_end_code_24c2',
    0x24C3: 'slmp_end_code_24c3',
    0x24C6: 'slmp_end_code_24c6',
    0x3008: 'slmp_end_code_3008',
    0x3019: 'slmp_end_code_3019',
    0x301A: 'slmp_end_code_301a',
    0x301B: 'slmp_end_code_301b',
    0x301C: 'slmp_end_code_301c',
    0x301D: 'slmp_end_code_301d',
    0x301E: 'slmp_end_code_301e',
    0x3020: 'slmp_end_code_3020',
    0x3022: 'slmp_end_code_3022',
    0x3023: 'slmp_end_code_3023',
    0x3026: 'slmp_end_code_3026',
    0x3040: 'slmp_end_code_3040',
    0x3060: 'slmp_end_code_3060',
    0x3C00: 'slmp_end_code_3c00',
    0x3C01: 'slmp_end_code_3c01',
    0x3C02: 'slmp_end_code_3c02',
    0x3C03: 'slmp_end_code_3c03',
    0x3C0F: 'slmp_end_code_3c0f',
    0x3C10: 'slmp_end_code_3c10',
    0x3C11: 'slmp_end_code_3c11',
    0x3C13: 'slmp_end_code_3c13',
    0x3C14: 'slmp_end_code_3c14',
    0x3C2F: 'slmp_end_code_3c2f',
    0x3E01: 'slmp_end_code_3e01',
    0xC001: 'slmp_end_code_c001',
    0xC012: 'slmp_end_code_c012',
    0xC013: 'slmp_end_code_c013',
    0xC015: 'slmp_end_code_c015',
    0xC016: 'slmp_end_code_c016',
    0xC018: 'slmp_end_code_c018',
    0xC020: 'slmp_end_code_c020',
    0xC021: 'slmp_end_code_c021',
    0xC022: 'slmp_end_code_c022',
    0xC024: 'slmp_end_code_c024',
    0xC025: 'slmp_end_code_c025',
    0xC026: 'slmp_end_code_c026',
    0xC027: 'slmp_end_code_c027',
    0xC028: 'slmp_end_code_c028',
    0xC029: 'slmp_end_code_c029',
    0xC035: 'slmp_end_code_c035',
    0xC040: 'slmp_end_code_c040',
    0xC050: 'slmp_end_code_c050',
    0xC051: 'slmp_end_code_c051',
    0xC052: 'slmp_end_code_c052',
    0xC053: 'slmp_end_code_c053',
    0xC054: 'slmp_end_code_c054',
    0xC055: 'slmp_end_code_c055',
    0xC056: 'slmp_end_code_c056',
    0xC057: 'slmp_end_code_c057',
    0xC058: 'slmp_end_code_c058',
    0xC059: 'slmp_end_code_c059',
    0xC05A: 'slmp_end_code_c05a',
    0xC05B: 'slmp_end_code_c05b',
    0xC05C: 'slmp_end_code_c05c',
    0xC05D: 'slmp_end_code_c05d',
    0xC05E: 'slmp_end_code_c05e',
    0xC05F: 'slmp_end_code_c05f',
    0xC060: 'slmp_end_code_c060',
    0xC061: 'slmp_end_code_c061',
    0xC070: 'slmp_end_code_c070',
    0xC071: 'slmp_end_code_c071',
    0xC072: 'slmp_end_code_c072',
    0xC073: 'slmp_end_code_c073',
    0xC075: 'slmp_end_code_c075',
    0xC081: 'slmp_end_code_c081',
    0xC083: 'slmp_end_code_c083',
    0xC084: 'slmp_end_code_c084',
    0xC085: 'slmp_end_code_c085',
    0xC0B2: 'slmp_end_code_c0b2',
    0xC0B3: 'slmp_end_code_c0b3',
    0xC0B6: 'slmp_end_code_c0b6',
    0xC0BA: 'slmp_end_code_c0ba',
    0xC0C4: 'slmp_end_code_c0c4',
    0xC0D0: 'slmp_end_code_c0d0',
    0xC0D1: 'slmp_end_code_c0d1',
    0xC0D3: 'slmp_end_code_c0d3',
    0xC0D4: 'slmp_end_code_c0d4',
    0xC0D5: 'slmp_end_code_c0d5',
    0xC0D6: 'slmp_end_code_c0d6',
    0xC0D7: 'slmp_end_code_c0d7',
    0xC0D8: 'slmp_end_code_c0d8',
    0xC0D9: 'slmp_end_code_c0d9',
    0xC0DA: 'slmp_end_code_c0da',
    0xC0DB: 'slmp_end_code_c0db',
    0xC0DE: 'slmp_end_code_c0de',
    0xC101: 'slmp_end_code_c101',
    0xC1A2: 'slmp_end_code_c1a2',
    0xC1A4: 'slmp_end_code_c1a4',
    0xC1A5: 'slmp_end_code_c1a5',
    0xC1A6: 'slmp_end_code_c1a6',
    0xC1A7: 'slmp_end_code_c1a7',
    0xC1A8: 'slmp_end_code_c1a8',
    0xC1A9: 'slmp_end_code_c1a9',
    0xC1AA: 'slmp_end_code_c1aa',
    0xC1AC: 'slmp_end_code_c1ac',
    0xC1AD: 'slmp_end_code_c1ad',
    0xC1AF: 'slmp_end_code_c1af',
    0xC1B0: 'slmp_end_code_c1b0',
    0xC1B1: 'slmp_end_code_c1b1',
    0xC1B2: 'slmp_end_code_c1b2',
    0xC1B3: 'slmp_end_code_c1b3',
    0xC1B4: 'slmp_end_code_c1b4',
    0xC1B8: 'slmp_end_code_c1b8',
    0xC1B9: 'slmp_end_code_c1b9',
    0xC1BA: 'slmp_end_code_c1ba',
    0xC1BB: 'slmp_end_code_c1bb',
    0xC1BC: 'slmp_end_code_c1bc',
    0xC1BD: 'slmp_end_code_c1bd',
    0xC1BE: 'slmp_end_code_c1be',
    0xC1BF: 'slmp_end_code_c1bf',
    0xC1C0: 'slmp_end_code_c1c0',
    0xC1C1: 'slmp_end_code_c1c1',
    0xC1C2: 'slmp_end_code_c1c2',
    0xC1C4: 'slmp_end_code_c1c4',
    0xC1C5: 'slmp_end_code_c1c5',
    0xC1C6: 'slmp_end_code_c1c6',
    0xC1C7: 'slmp_end_code_c1c7',
    0xC1C8: 'slmp_end_code_c1c8',
    0xC1C9: 'slmp_end_code_c1c9',
    0xC1CA: 'slmp_end_code_c1ca',
    0xC1CB: 'slmp_end_code_c1cb',
    0xC1CC: 'slmp_end_code_c1cc',
    0xC1CD: 'slmp_end_code_c1cd',
    0xC1D0: 'slmp_end_code_c1d0',
    0xC1D2: 'slmp_end_code_c1d2',
    0xC1D3: 'slmp_end_code_c1d3',
    0xC200: 'slmp_end_code_c200',
    0xC201: 'slmp_end_code_c201',
    0xC202: 'slmp_end_code_c202',
    0xC203: 'slmp_end_code_c203',
    0xC204: 'slmp_end_code_c204',
    0xC205: 'slmp_end_code_c205',
    0xC207: 'slmp_end_code_c207',
    0xC208: 'slmp_end_code_c208',
    0xC400: 'slmp_end_code_c400',
    0xC401: 'slmp_end_code_c401',
    0xC402: 'slmp_end_code_c402',
    0xC403: 'slmp_end_code_c403',
    0xC404: 'slmp_end_code_c404',
    0xC405: 'slmp_end_code_c405',
    0xC406: 'slmp_end_code_c406',
    0xC407: 'slmp_end_code_c407',
    0xC408: 'slmp_end_code_c408',
    0xC410: 'slmp_end_code_c410',
    0xC412: 'slmp_end_code_c412',
    0xC413: 'slmp_end_code_c413',
    0xC414: 'slmp_end_code_c414',
    0xC417: 'slmp_end_code_c417',
    0xC420: 'slmp_end_code_c420',
    0xC421: 'slmp_end_code_c421',
    0xC430: 'slmp_end_code_c430',
    0xC431: 'slmp_end_code_c431',
    0xC440: 'slmp_end_code_c440',
    0xC441: 'slmp_end_code_c441',
    0xC442: 'slmp_end_code_c442',
    0xC443: 'slmp_end_code_c443',
    0xC444: 'slmp_end_code_c444',
    0xC445: 'slmp_end_code_c445',
    0xC446: 'slmp_end_code_c446',
    0xC447: 'slmp_end_code_c447',
    0xC448: 'slmp_end_code_c448',
    0xC449: 'slmp_end_code_c449',
    0xC44A: 'slmp_end_code_c44a',
    0xC44B: 'slmp_end_code_c44b',
    0xC44C: 'slmp_end_code_c44c',
    0xC44D: 'slmp_end_code_c44d',
    0xC44E: 'slmp_end_code_c44e',
    0xC44F: 'slmp_end_code_c44f',
    0xC610: 'slmp_end_code_c610',
    0xC611: 'slmp_end_code_c611',
    0xC612: 'slmp_end_code_c612',
    0xC613: 'slmp_end_code_c613',
    0xC614: 'slmp_end_code_c614',
    0xC615: 'slmp_end_code_c615',
    0xC616: 'slmp_end_code_c616',
    0xC617: 'slmp_end_code_c617',
    0xC618: 'slmp_end_code_c618',
    0xC619: 'slmp_end_code_c619',
    0xC620: 'slmp_end_code_c620',
    0xC621: 'slmp_end_code_c621',
    0xC622: 'slmp_end_code_c622',
    0xC623: 'slmp_end_code_c623',
    0xC700: 'slmp_end_code_c700',
    0xC701: 'slmp_end_code_c701',
    0xC702: 'slmp_end_code_c702',
    0xC703: 'slmp_end_code_c703',
    0xC704: 'slmp_end_code_c704',
    0xC705: 'slmp_end_code_c705',
    0xC706: 'slmp_end_code_c706',
    0xC707: 'slmp_end_code_c707',
    0xC708: 'slmp_end_code_c708',
    0xC709: 'slmp_end_code_c709',
    0xC810: 'slmp_end_code_c810',
    0xC811: 'slmp_end_code_c811',
    0xC812: 'slmp_end_code_c812',
    0xC813: 'slmp_end_code_c813',
    0xC814: 'slmp_end_code_c814',
    0xC815: 'slmp_end_code_c815',
    0xC816: 'slmp_end_code_c816',
    0xC840: 'slmp_end_code_c840',
    0xC842: 'slmp_end_code_c842',
    0xC843: 'slmp_end_code_c843',
    0xC844: 'slmp_end_code_c844',
    0xC860: 'slmp_end_code_c860',
    0xC861: 'slmp_end_code_c861',
    0xC862: 'slmp_end_code_c862',
    0xC863: 'slmp_end_code_c863',
    0xC864: 'slmp_end_code_c864',
    0xC865: 'slmp_end_code_c865',
    0xC866: 'slmp_end_code_c866',
    0xC867: 'slmp_end_code_c867',
    0xC868: 'slmp_end_code_c868',
    0xC869: 'slmp_end_code_c869',
    0xC86A: 'slmp_end_code_c86a',
    0xC86B: 'slmp_end_code_c86b',
    0xC86C: 'slmp_end_code_c86c',
    0xCEE0: 'slmp_end_code_cee0',
    0xCEE1: 'slmp_end_code_cee1',
    0xCEE2: 'slmp_end_code_cee2',
    0xCF10: 'slmp_end_code_cf10',
    0xCF20: 'slmp_end_code_cf20',
    0xCF30: 'slmp_end_code_cf30',
    0xCF31: 'slmp_end_code_cf31',
    0xCF70: 'slmp_end_code_cf70',
    0xCF71: 'slmp_end_code_cf71',
    0xCF80: 'slmp_end_code_cf80',
    0xCF81: 'slmp_end_code_cf81',
    0xCF82: 'slmp_end_code_cf82',
    0xCF83: 'slmp_end_code_cf83',
    0xCF84: 'slmp_end_code_cf84',
    0xCF85: 'slmp_end_code_cf85',
    0xCF8A: 'slmp_end_code_cf8a',
    0xCF8C: 'slmp_end_code_cf8c',
    0xCFB0: 'slmp_end_code_cfb0',
    0xCFB1: 'slmp_end_code_cfb1',
    0xCFB2: 'slmp_end_code_cfb2',
    0xCFB3: 'slmp_end_code_cfb3',
    0xCFB4: 'slmp_end_code_cfb4',
    0xCFB5: 'slmp_end_code_cfb5',
    0xCFBD: 'slmp_end_code_cfbd',
    0xCFBE: 'slmp_end_code_cfbe',
    0xCFBF: 'slmp_end_code_cfbf',
}

_END_CODE_MESSAGES_EN: dict[int, str] = {
    0x1080: 'The number of writes to the flash ROM has exceeded 100000.',
    0x1120: 'Clock setting has failed when the system is powered on or the CPU module is reset.',
    0x1124: '・The default gateway is not set correctly.・The gateway IP address is not set correctly.・The default gateway/gateway IP address (network address after the subnet mask) is different from that of the IP address of the own node.',
    0x1128: 'The port number is incorrect.',
    0x1129: 'The port number of the external device is not set correctly.',
    0x112C: 'The request using all stations specification has failed.',
    0x112D: 'The data was sent to the external device while the IP address setting of the device set in "External Device Configuration" under "Basic Settings" was incorrect.',
    0x112E: 'A connection could not be established in the open processing.',
    0x1133: 'The response send failed during socket communications or communications using the fixed buffer.',
    0x1134: 'A TCP ULP timeout error has occurred in the TCP/IP communication. (The external device does not send an ACK response.)',
    0x1152: '・The IP address is not set correctly.・The same IP address has been set to port 1 and port 2 of the Ethernet-equipped module.',
    0x1155: '・The specified connection was already closed in TCP/IP communications.・Open processing is not performed.',
    0x1157: '・The specified connection was already closed in UDP/IP communications.・Open processing is not performed.',
    0x1158: '・The receive buffer or send buffer is not sufficient.・The window size of the external device is not sufficient.',
    0x1165: 'Data was not sent correctly with UDP/IP.',
    0x1166: 'Data was not sent correctly with TCP/IP.',
    0x1167: 'Unsent data found, but could not be sent.',
    0x1180: '・The same IP address has been set as the system A IP address, system B IP address, and/or control system IP address.・Network addresses of the system A IP address, system B IP address, and control system IP address are different.',
    0x1801: 'IP address of the external device could not be acquired.',
    0x1811: 'An error was detected in the CPU module.',
    0x1830: 'Number of reception requests of transient transmission (link dedicated instruction) exceeded upper limit of simultaneously processable requests.',
    0x1845: 'Too many processings of transient transmission (link dedicated instruction) and cannot perform transient transmission.',
    0x1F07: 'An error occurs in the protocol data set in "Simple Device Communication Setting".',
    0x20E0: 'The module cannot communicate with the CPU module.',
    0x2160: 'Overlapping IP addresses were detected.',
    0x2220: '・A network module having the firmware version not supporting the simple CPU communication function is used.・The number of simple CPU communication settings is 65 or more.・The parameter setting is corrupted.',
    0x2221: 'The set value is out of the range.',
    0x2250: 'The protocol setting data stored in the CPU module is not for the Ethernet-equipped module.',
    0x24C0: 'An error was detected on the system bus.',
    0x24C1: 'An error was detected on the system bus.',
    0x24C2: 'An error was detected on the system bus.',
    0x24C3: 'An error was detected on the system bus.',
    0x24C6: 'An error was detected on the system bus.',
    0x3008: 'In the redundant system with redundant extension base unit, a module name other than "RJ71EN71(E+E)" and "RJ71EN71(Q)" is set on the extension base.',
    0x3019: '・When mounting a module on the main base unit in the redundant system, "Not Use" is set to "To Use or Not to Use Redundant System Settings" under "Application Settings".・When mounting a module on the extension base unit in the redundant system with redundant extension base unit, "Use" is set to "To Use or Not to Use Redundant System Settings" under "Application Settings".',
    0x301A: 'When mounting a module on the extension base unit in the redundant system with redundant extension base unit, "Enable" is set to "Dynamic Routing" under "Application Settings".',
    0x301B: 'When mounting a module on the extension base unit in the redundant system with redundant extension base unit, "Use" is set to "IP Packet Transfer Function" under "Application Settings".',
    0x301C: '・Incorrect protocol data is set in "Simple Device Communication Setting".・A packet used is not supported by the current firmware version.',
    0x301D: 'A function used is not supported by the current firmware version.',
    0x301E: 'The "Resource Setting" is incorrectly set in "Simple Device Communication Setting" of the port 1 or port 2.',
    0x3020: 'A value of the port number is out of range.',
    0x3022: 'The total number of external devices and communication destinations set using parameters exceeds 64.',
    0x3023: '"Port No. Host Station" set in "Simple Device Communication Setting" overlaps a value set for another function.',
    0x3026: 'The module does not support "Extension 2", which is set in "Resource Setting" under "Simple Device Communication Setting".',
    0x3040: 'Response data of the dedicated instruction cannot be created.',
    0x3060: 'The send/receive data size exceeds the allowable range.',
    0x3C00: '・A hardware failure has been detected.・In a redundant system configuration, the control system was powered off or reset without the tracking cable connected.',
    0x3C01: '・A hardware failure has been detected.・In a redundant system configuration, the control system was powered off or reset without the tracking cable connected.',
    0x3C02: '・A hardware failure has been detected.・In a redundant system configuration, the control system was powered off or reset without the tracking cable connected.',
    0x3C03: '・A hardware failure has been detected.・In a redundant system configuration, the control system was powered off or reset without the tracking cable connected.',
    0x3C0F: 'A hardware failure has been detected.',
    0x3C10: 'A hardware failure has been detected.',
    0x3C11: 'A hardware failure has been detected.',
    0x3C13: 'A hardware failure has been detected.',
    0x3C14: 'A hardware failure has been detected.',
    0x3C2F: 'An error was detected in the memory.',
    0x3E01: 'Network type of the own station is unexpected setting.',
    0xC001: '・The IP address setting value of the E71 for the initial processing is incorrect.・The setting value of the subnet mask field for the router relay function is incorrect.',
    0xC012: 'The port number used in a connection already opened is set. (For TCP/IP)',
    0xC013: 'The port number used in a connection already opened is set. (For UDP/IP)',
    0xC015: '・The specified IP address of the external device for the open processing is incorrect.・The specified IP address of the external device of the dedicated instruction is incorrect.',
    0xC016: 'The open processing of the connection specified for pairing open has been already completed.',
    0xC018: 'The specified IP address of the external device is incorrect.',
    0xC020: 'The send/receive data length exceeds the allowable range.',
    0xC021: 'An abnormal end response was received for communications using the fixed buffer and random access buffer.',
    0xC022: '・A response could not be received within the response monitoring timer value.・The connection with the external device was closed while waiting for a response.',
    0xC024: '・Communications using the fixed buffer or communications using a random access buffer were executed when communication method is set to the "Predefined Protocol" connection.・Predefined protocol was executed when communication method is set to "Fixed Buffer (Procedure Exist)" or "Fixed Buffer (No Procedure)" connection.',
    0xC025: 'There is an error in the usage setting area when starting the open processing by the CONOPEN/OPEN instruction or I/O signals.',
    0xC026: 'An error has occurred when reading/writing/verifying the predefined protocol setting data.',
    0xC027: 'Message send of the socket communications has failed.',
    0xC028: 'Message send of the fixed buffer has failed.',
    0xC029: '・Description of control data is not correct.・Open instruction was executed through open settings parameter even though parameters are not set.',
    0xC035: 'The existence of the external device could not be checked within the response monitoring timer value.',
    0xC040: '・Not all the data could be received within the response monitoring timer value.・Sufficient data for the data length could not be received.・The remaining part of the message divided at the TCP/IP level could not be received within the response monitoring timer value.',
    0xC050: 'When "ASCII" has been selected in the communication data code setting of the Ethernet-equipped module, ASCII code data which cannot be converted into binary code data has been received.',
    0xC051: '・The number of read/write points from/to the device of SLMP message is out of the allowable range in the CPU module (in units of words).・The number of write points for the long counter of SLMP message is not in two-word units.',
    0xC052: 'The number of read/write points from/to the device of SLMP message is out of the allowable range in the CPU module (in units of bits).',
    0xC053: 'The number of read/write points from/to the random device of SLMP message is out of the allowable range in the CPU module (in units of bits).',
    0xC054: 'The number of read/write points from/to the random device of SLMP message is out of the allowable range in the CPU module (in units of words, double words).',
    0xC055: 'The read/write size from/to the file data of SLMP message is out of the allowable range.',
    0xC056: 'The read/write request exceeds the largest address.',
    0xC057: 'The request data length of the SLMP message does not match with the number of data in the character (a part of text).',
    0xC058: 'The request data length of the SLMP message after the ASCII/binary conversion does not match with the number of data in the character (a part of text).',
    0xC059: '・The specified command and subcommand of the SLMP message are incorrect・The function which is not supported by the target device was executed.',
    0xC05A: 'The Ethernet-equipped module cannot read/write data from/to the device specified by the SLMP message.',
    0xC05B: 'The Ethernet-equipped module cannot read/write data from/to the device specified by the SLMP message.',
    0xC05C: '・The received request data of the SLMP message is incorrect.・The setting value of the communication setting when the iQSS function is executed is out of range.・When the iQSS function is executed, the items of communication setting which cannot be set on the target device are set.・When the iQSS function is executed, the required setting items have not been set to the target device.',
    0xC05D: 'The "Monitor Request" command is received before the monitor registration is performed by "Monitor Registration/Clear" command of the SLMP message.',
    0xC05E: '・The time between received the SLMP message from the Ethernet-equipped module and returned response from the access destination exceeded the monitoring timer value set in the SLMP command.・An SLMP request message to which a command without a response message is specified is send to a module with the other network number as an access destination.',
    0xC05F: 'This request cannot be executed to the access destination specified by the SLMP message.',
    0xC060: 'The request details for bit devices of the SLMP message is incorrect.',
    0xC061: '・The request data length of the SLMP message does not match with the number of data in the character (a part of text).・The write data length specified by the label write command is not even byte.・When the iQSS function is executed, incorrect frame is received.',
    0xC070: 'The device memory cannot be extended for the access destination specified by the SLMP message.',
    0xC071: 'The number of device points for data read/write set for modules other than an R/Q/QnACPU is out of the range.',
    0xC072: 'The request details of the SLMP message is incorrect. (For example, a request for data read/write in bit units has been issued to a word device.)',
    0xC073: 'The access destination of the SLMP message cannot issue this request. (For example, the number of double word access points cannot be specified for modules other than an R/Q/QnACPU.)',
    0xC075: 'The request data length for the label access is out of range.',
    0xC081: 'The termination processing for the Ethernet-equipped module that is involved with the reinitialization processing is being performed, and arrival of link dedicated instructions cannot be checked.',
    0xC083: 'The communication processing was abnormally ended in the link dedicated instruction communications',
    0xC084: 'The communication processing was abnormally ended in the link dedicated instruction communications',
    0xC085: "The target station's channel specified by the link dedicated instruction SEND is currently in use.",
    0xC0B2: 'There is no sufficient space in the receive buffer or the send buffer of the relay station or external station for the MELSOFT connection, link dedicated instructions, or SLMP. (Send · receive buffer full error)',
    0xC0B3: 'A request that cannot be processed was issued from the CPU module.',
    0xC0B6: 'The channel specified by the dedicated instruction is out of the range.',
    0xC0BA: 'Since the close processing is in execution using the CONCLOSE/CLOSE instruction, a send request cannot be accepted.',
    0xC0C4: 'The UINI instruction has been executed during communications.',
    0xC0D0: 'The specified data length of the link dedicated instruction is incorrect.',
    0xC0D1: 'The number of resends of the link dedicated instruction is incorrect.',
    0xC0D3: 'The number of relay stations to communicate with other networks exceeds the allowable range.',
    0xC0D4: 'The number of relay stations to communicate with other networks exceeds the allowable range.',
    0xC0D5: 'The number of retries of the link dedicated instruction is incorrect.',
    0xC0D6: 'The network number or station number of the link dedicated instruction is incorrect.',
    0xC0D7: 'Data were sent without the initial processing completed.',
    0xC0D8: 'The number of specified blocks exceeded the range.',
    0xC0D9: 'The specified subcommand of the SLMP message is incorrect.',
    0xC0DA: 'A response to the PING test could not be received within the time of the communication time check.',
    0xC0DB: 'The IP address and host name of the target module where the PING test is execute are incorrect.',
    0xC0DE: 'Data could not be received within the specified arrival monitoring time.',
    0xC101: 'A response could not be received from the DNS server.',
    0xC1A2: '・A response to the request could not be received.・In transient transmission, the number of relay to other networks exceeded seven.',
    0xC1A4: '・Any of the specified command, subcommand, or request destination module I/O number of the SLMP message is incorrect.・The specified clear function set by the ERRCLEAR instruction is incorrect.・The specified information to be read set by the ERRRD instruction is incorrect.・The Ethernet diagnostics, CC-Link IE Field Network diagnostics, or CC-Link IE Controller Network diagnostics was tried to be used when the engineering tool is directly connected to the Ethernet port of the RJ71EN71.・The function which is not supported by the target device was executed.',
    0xC1A5: 'The specified target station or clear target is incorrect.',
    0xC1A6: 'The specified connection number is incorrect.',
    0xC1A7: 'The specified network number is incorrect.',
    0xC1A8: 'The specified station number is incorrect.',
    0xC1A9: 'The specified device number is incorrect.',
    0xC1AA: 'The specified device name is incorrect.',
    0xC1AC: 'The specified number of resends is incorrect.',
    0xC1AD: 'The specified data length is incorrect.',
    0xC1AF: 'The specified port number is incorrect.',
    0xC1B0: 'The open processing of the specified connection has been already completed.',
    0xC1B1: 'The open processing of the specified connection has not been completed.',
    0xC1B2: 'The open or close processing using CONOPEN/CONCLOSE/OPEN/CLOSE instruction is being executed in the specified connection.',
    0xC1B3: 'Another send or receive instruction is being executed in the specified channel.',
    0xC1B4: 'The specified arrival monitoring time is incorrect.',
    0xC1B8: 'The RECV instruction was executed for the channel that had not received data.',
    0xC1B9: 'The CONOPEN/OPEN instruction cannot be executed for the specified connection.',
    0xC1BA: 'The dedicated instruction was executed with the initialization not completed.',
    0xC1BB: 'The target station CPU type of the link dedicated instruction is incorrect.',
    0xC1BC: 'The target network number of the link dedicated instruction is incorrect.',
    0xC1BD: 'The target station number of the link dedicated instruction is incorrect.',
    0xC1BE: 'The command code of the dedicated instruction is incorrect.',
    0xC1BF: 'The channel used in the dedicated instruction is incorrect.',
    0xC1C0: 'The transient data is incorrect.',
    0xC1C1: 'The transient data is incorrect.',
    0xC1C2: 'When the dedicated instruction was executed, data was received twice.',
    0xC1C4: 'The arrival check of the link dedicated instruction was completed with an error.',
    0xC1C5: 'A dedicated instruction which the target station does not support was executed.',
    0xC1C6: 'The execution or error completion type of the dedicated instruction is incorrect.',
    0xC1C7: 'The request type of the REQ instruction is incorrect.',
    0xC1C8: 'The channel specified in the dedicated instruction is in use.',
    0xC1C9: 'The device specification for the ZNRD/ZNWR instruction is not correct.',
    0xC1CA: 'The device specification for the ZNRD/ZNWR instruction is not correct.',
    0xC1CB: 'The transient data is incorrect.',
    0xC1CC: 'A response of the data length that exceeds the allowable range was received by the SLMPSND instruction.',
    0xC1CD: 'Message send of the SLMPSND instruction has failed.',
    0xC1D0: 'The requested module I/O No. of the dedicated instruction is incorrect.',
    0xC1D2: 'The target station IP address of the link dedicated instruction is incorrect.',
    0xC1D3: 'The dedicated instruction not supported by the communication method of the connection was executed.',
    0xC200: 'The remote password is incorrect.',
    0xC201: 'The remote password status of the port used for communications is in the lock status.',
    0xC202: 'When another station was accessed, the remote password could not be unlocked.',
    0xC203: 'An error has occurred by checking the remote password.',
    0xC204: 'The device is different from the one requesting the remote password unlock processing.',
    0xC205: 'When another station was accessed, the remote password could not be unlocked.',
    0xC207: 'The file name has too many characters.',
    0xC208: 'The password length is out of range.',
    0xC400: 'The ECPRTCL instruction was executed when Predefined protocol ready is not completed.',
    0xC401: 'The protocol number specified by the ECPRTCL instruction is not registered in the Ethernet-equipped module.',
    0xC402: 'An error has occurred in the protocol setting data registered in the Ethernet-equipped module and the ECPRTCL instruction cannot be executed.',
    0xC403: 'Multiple dedicated instructions was executed simultaneously.',
    0xC404: 'The protocol being executed by the ECPRTCL instruction was canceled.',
    0xC405: 'The protocol number specified by the ECPRTCL instruction is incorrect.',
    0xC406: 'The continuous protocol execution count of the ECPRTCL instruction is incorrect.',
    0xC407: 'The connection number specified by the ECPRTCL instruction is incorrect.',
    0xC408: 'An error has occurred when the send processing of the predefined protocol using the ECPRTCL instruction was performed.',
    0xC410: 'Receive waiting time of the ECPRTCL instruction timed out.',
    0xC412: 'The data which cannot be converted from ASCII to binary code was received.',
    0xC413: 'The number of digits of the received data using the predefined protocol is not sufficient.',
    0xC414: 'The number of digits of the received data using the predefined protocol is incorrect.',
    0xC417: 'The data length or data quantity of the received data using the predefined protocol is out of range.',
    0xC420: 'Protocol setting data write has failed.',
    0xC421: 'Writing was requested to the module whose flash ROM write count had exceeded the limit.',
    0xC430: 'Protocol setting data was written during the ECPRTCL instruction execution.',
    0xC431: 'Close processing of the connection was performed during the ECPRTCL instruction execution.',
    0xC440: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC441: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC442: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC443: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC444: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC445: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC446: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC447: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC448: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC449: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44A: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44B: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44C: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44D: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44E: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC44F: 'A communication error has occurred with an engineering tool when executing the Ethernet diagnostics.',
    0xC610: 'The module processing was completed with an error.',
    0xC611: 'The module processing was completed with an error.',
    0xC612: 'The module processing was completed with an error.',
    0xC613: 'The module processing was completed with an error.',
    0xC614: 'The module processing was completed with an error.',
    0xC615: 'The module processing was completed with an error.',
    0xC616: 'Connection of the control port to the FTP server failed.',
    0xC617: 'Disconnection of the control port to the FTP server failed.',
    0xC618: 'Login to the FTP server failed.',
    0xC619: 'Execution of the FTP command to the FTP server failed.',
    0xC620: 'Connection of the data transfer port to the FTP server failed.',
    0xC621: 'Disconnection of the data transfer port to the FTP server failed.',
    0xC622: 'An error has occurred during file transfer to the FTP server.',
    0xC623: 'A response could not be received from the FTP server.',
    0xC700: 'The module processing was completed with an error.',
    0xC701: 'The IP address (network number) setting is incorrect in communications using the IP packet transfer function.',
    0xC702: 'The IP address (station number) setting is incorrect in communications using the IP packet transfer function.',
    0xC703: 'The destination IP address (upper level) setting is incorrect in communications using the IP packet transfer function.',
    0xC704: 'The destination IP address (lower level) setting is incorrect in communications using the IP packet transfer function.',
    0xC705: 'The module processing was completed with an error.',
    0xC706: 'The module processing was completed with an error.',
    0xC707: 'The module processing was completed with an error.',
    0xC708: 'When communicating with the IP packet transfer function, "IP Packet Transfer Function" is set as "Not Use" in "IP Packet Transfer Setting" under "Application Settings" of the Ethernet-equipped module connected with the Ethernet devices.',
    0xC709: 'A communication error has occurred with MELSOFT direct connection.',
    0xC810: 'Remote password authentication has failed when required. Set a correct password and retry.',
    0xC811: 'Remote password authentication has failed when required. Set a correct password and retry after 1 minute.',
    0xC812: 'Remote password authentication has failed when required. Set a correct password and retry after 5 minutes.',
    0xC813: 'Remote password authentication has failed when required. Set a correct password and retry after 15 minutes.',
    0xC814: 'Remote password authentication has failed when required. Set a correct password and retry after 60 minutes.',
    0xC815: 'Remote password authentication has failed when required. Set a correct password and retry after 60 minutes.',
    0xC816: 'The security function was activated and remote password authentication cannot be performed.',
    0xC840: 'Number of transient request exceeded the upper limit of simultaneously processable requests.',
    0xC842: 'The routing setting is not set to reach to the destination network number.',
    0xC843: 'Link dedicated instruction that cannot be executed on the network type were executed.',
    0xC844: 'Incorrect frame is received.・Unsupported pre-conversion protocol・Unsupported frame type・Application header variable part・Application header HDS・Application header RTP・Read command not requiring response',
    0xC860: 'The CPU response monitoring timer issued a timeout during MODBUS/TCP communications.',
    0xC861: 'A request message containing an unsupported function code was received during MODBUS/TCP communications.',
    0xC862: 'A request message containing an unsupported sub-code was received during MODBUS/TCP communications.',
    0xC863: 'The MODBUS device assignment parameters have not been set for the MODBUS device specified in the received request message in MODBUS/TCP communications.',
    0xC864: 'The range of the MODBUS devices specified in the received request message exceeded the setting range of the MODBUS device assignment parameters in MODBUS/TCP communications.',
    0xC865: 'The range of the MODBUS devices specified in the received request message exceeded the upper limit for the MODBUS devices in MODBUS/TCP communications. (The upper limit of extended file register is 10000 and the upper limit of the MODBUS device is 65536.)',
    0xC866: 'The start address and the number of access points of the MODBUS device specified in the received request message are incorrect in MODBUS/TCP communications.',
    0xC867: 'The number of write points specified for the received request message does not match with the specified number of bytes in MODBUS/TCP communications.',
    0xC868: 'The received write data size does not match with the specified number of bytes in MODBUS/TCP communications.',
    0xC869: 'The value of the reference type specified in the received request message (FC20, FC21) is incorrect in MODBUS/TCP communications.',
    0xC86A: 'The content of the data part of the received request message is incorrect in MODBUS/TCP communications.The size of the received request message is smaller than the minimum size required for the function code, or larger than the maximum size required for the function code.',
    0xC86B: 'The content of MBAP header of the received request message is incorrect in MODBUS/TCP communications.',
    0xC86C: 'The number of received request messages exceeded the number that can be received simultaneously.',
    0xCEE0: 'The devices supporting iQSS which were detected by the other peripheral device, or other iQSS functions were executed while the automatic detection of connected devices is in process.',
    0xCEE1: 'Incorrect frame is received.',
    0xCEE2: 'Incorrect frame is received.',
    0xCF10: 'Incorrect frame is received.',
    0xCF20: '・The setting value of the communication setting is out of range.・The items of communication setting which cannot be set on the target device are set.・The required setting items have not been set to the target device.',
    0xCF30: 'The parameter which is not supported by the target device was specified.',
    0xCF31: 'Incorrect frame is received.',
    0xCF70: 'An error occurred on the Ethernet communication path.',
    0xCF71: 'A timeout error has occurred.',
    0xCF80: 'During the simple device communication, communications with the communication destination cannot be executed. Or the external device is disconnected.',
    0xCF81: 'During the simple device communication, the communication has failed due to a communication timeout.',
    0xCF82: 'During the simple device communication, the "Send/Receive Data Length Storage Area" or "Send/Receive Data Count Storage Area" value in "Non-conversion Variable (variable length)" or "Conversion Variable (variable length)" of "Variable Number of Data" set for the send packet exceeds the range that can be set.',
    0xCF83: 'During the simple device communication, the data size of send data has been 0.',
    0xCF84: 'During the simple device communication, sending the send packet has failed.',
    0xCF85: 'Data outside the range was set during simple device communication.',
    0xCF8A: 'During the simple device communication, the request to the CPU module has been failed.',
    0xCF8C: 'During the simple device communication, the receive data does not match with any of the receive packets set using the parameter.',
    0xCFB0: 'Sending data failed due to a resend timeout while the simple CPU communication.',
    0xCFB1: 'Communications with the communication destination do not executed while the simple CPU communication. Or the external device is disconnected.',
    0xCFB2: 'The same specified own station port number is already used for the simple CPU communication.',
    0xCFB3: 'The request to the CPU module has failed while the simple CPU communication.',
    0xCFB4: 'An abnormal response was received from the communication destination while the simple CPU communication.',
    0xCFB5: 'The frame received from the communication destination is incorrect while the simple CPU communication.',
    0xCFBD: 'The device specified as the communication destination is out of specification range for the simple CPU communication.',
    0xCFBE: 'A communication error has occurred with an engineering tool during the simple CPU communication diagnostics.',
    0xCFBF: 'The simple CPU communication cannot be executed.',
}

_END_CODE_MESSAGES_JA: dict[int, str] = {
    0x1080: 'フラッシュROMへの書込み回数が10万回を超えた。',
    0x1120: 'シーケンサ電源ON/リセット時の時計設定に失敗した。',
    0x1124: '・デフォルトゲートウェイの設定値に誤りがある。・ゲートウェイIPアドレスの設定値に誤りがある。・デフォルトゲートウェイ/ゲートウェイIPアドレス(サブネットマスク後のネットワークアドレス)が自ノードのIPアドレスのネットワークアドレスと異なる。',
    0x1128: 'ポート番号に誤りがある。',
    0x1129: '相手機器のポート番号の設定値に誤りがある。',
    0x112C: '全局指定による要求に失敗した。',
    0x112D: '”基本設定”の”相手機器接続構成設定”で設定した接続する機器のIPアドレスの設定に誤りがある状態で，その機器に対して送信を行った。',
    0x112E: 'オープン処理で，コネクションが確立されなかった。',
    0x1133: 'ソケット通信または固定バッファによる交信でレスポンス送信に失敗した。',
    0x1134: 'TCP/IPの交信で，TCP ULPタイムアウトエラーが発生した。(相手機器からACKが返されない)',
    0x1152: '・IPアドレスの設定値に誤りがある。・Ethernet搭載ユニットのポート1とポート2のIPアドレスが重複している。',
    0x1155: '・TCP/IP交信で指定したコネクションがすでにクローズされている。・オープン処理が実施されていない。',
    0x1157: '・UDP/IP交信で指定したコネクションがすでにクローズされている。・オープン処理が実施されていない。',
    0x1158: '・受信バッファまたは送信バッファが不足している。・相手機器のウィンドウサイズが不足している。',
    0x1165: 'UDP/IPによる送信が正常に行えなかった。',
    0x1166: 'TCP/IPによる送信が正常に行えなかった。',
    0x1167: '未送信のデータがあるが，残りのデータを送信できなかった。',
    0x1180: '・A系IPアドレス，B系IPアドレス，制御系IPアドレスに重複が存在する。・A系IPアドレス，B系IPアドレス，制御系IPアドレスのネットワークアドレスが異なっている。',
    0x1801: '送信相手機器のIPアドレスが取得できない。',
    0x1811: 'CPUユニットの異常を検出した。',
    0x1830: 'トランジェント伝送(リンク専用命令)の受信要求数が，同時処理可能な上限を超過した。',
    0x1845: 'トランジェント伝送(リンク専用命令)の処理数が多すぎてトランジェント伝送が実行できない。',
    0x1F07: '”シンプル機器通信設定”で設定したプロトコルデータに誤りがある。',
    0x20E0: 'CPUユニットと通信できない。',
    0x2160: 'IPアドレスの重複を検出した。',
    0x2220: '・シンプルCPU通信機能に対応していないファームウェアバージョンのネットワークユニットを使用している。・シンプルCPU通信設定が65以上設定されている。・パラメータの内容が壊れている。',
    0x2221: 'パラメータの設定値が使用可能な範囲を超えている。',
    0x2250: 'CPUユニットに格納されているプロトコル設定データが，Ethernet搭載ユニット用ではない。',
    0x24C0: 'システムバスの異常を検出した。',
    0x24C1: 'システムバスの異常を検出した。',
    0x24C2: 'システムバスの異常を検出した。',
    0x24C3: 'システムバスの異常を検出した。',
    0x24C6: 'システムバスの異常を検出した。',
    0x3008: '二重化増設ベース構成において，増設ベース上のユニット形名に”RJ71EN71(E+E)”，”RJ71EN71(Q)”以外を選択している。',
    0x3019: '・二重化システムにおいて基本ベースに装着時，”応用設定”の”二重化設定使用有無”が”使用しない”に設定されている。・二重化増設ベース構成において増設ベースに装着時，”応用設定”の”二重化設定使用有無”が”使用する”に設定されている。',
    0x301A: '二重化増設ベース構成において増設ベースに装着時，”応用設定”の”動的ルーチング設定”が”有効”に設定されている。',
    0x301B: '二重化増設ベース構成において増設ベースに装着時，”応用設定”の”IPパケット中継機能使用有無”が”使用する”に設定されている。',
    0x301C: '・”シンプル機器通信設定”で設定したプロトコルデータに誤りがある。・本ファームウェアバージョンでは対応していないパケットを使用した。',
    0x301D: '本ファームウェアバージョンでは対応していない機能を使用した。',
    0x301E: 'ポート1またはポート2の”シンプル機器通信設定”で設定している”リソース設定”の設定が誤っている。',
    0x3020: 'システムポート番号の値が範囲外になっている。',
    0x3022: 'パラメータで設定した相手機器と交信相手の合計が64を超えている。',
    0x3023: '”シンプル機器通信設定”で設定した”ポート番号 自局”が，他機能で設定した値と重複している。',
    0x3026: '本ユニットが”シンプル機器通信設定”で設定している”リソース設定”の”拡張2”に対応していない。',
    0x3040: '専用命令の応答データの作成ができない。',
    0x3060: '送受信データサイズが許容範囲を超えている。',
    0x3C00: '・ハードウェアの異常を検出した。・二重化システム構成の場合，トラッキングケーブルが接続されていない状態で，制御系を電源OFFまたはリセットした。',
    0x3C01: '・ハードウェアの異常を検出した。・二重化システム構成の場合，トラッキングケーブルが接続されていない状態で，制御系を電源OFFまたはリセットした。',
    0x3C02: '・ハードウェアの異常を検出した。・二重化システム構成の場合，トラッキングケーブルが接続されていない状態で，制御系を電源OFFまたはリセットした。',
    0x3C03: '・ハードウェアの異常を検出した。・二重化システム構成の場合，トラッキングケーブルが接続されていない状態で，制御系を電源OFFまたはリセットした。',
    0x3C0F: 'ハードウェアの異常を検出した。',
    0x3C10: 'ハードウェアの異常を検出した。',
    0x3C11: 'ハードウェアの異常を検出した。',
    0x3C13: 'ハードウェアの異常を検出した。',
    0x3C14: 'ハードウェアの異常を検出した。',
    0x3C2F: 'メモリの異常を検出した。',
    0x3E01: '自局のネットワーク種別が想定外の設定となっている。',
    0xC001: '・イニシャル処理時の，自ユニットのIPアドレスの設定値に誤りがある。・ルータ中継機能を使用時，サブネットマスクフィールドの設定値に誤りがある。',
    0xC012: 'オープンしているコネクションで使用しているポート番号を設定した。(TCP/IPの場合)',
    0xC013: 'オープンしているコネクションで使用しているポート番号を設定した。(UDP/IPの場合)',
    0xC015: '・オープン処理時の，相手機器のIPアドレスの設定値に誤りがある。・専用命令の相手機器IPアドレスの設定に誤りがある。',
    0xC016: 'ペアリングオープンのコネクションは，すでにオープン処理されている。',
    0xC018: '相手機器IPアドレスの設定に誤りがある。',
    0xC020: '送受信データ長が許容範囲を超えている。',
    0xC021: '固定バッファ，ランダムアクセスバッファによる送信に対して，異常終了のレスポンスを受信した。',
    0xC022: '・レスポンス監視タイマ値以内に，レスポンスを受信できなかった。・レスポンス待ち中に該当コネクションがクローズされた。',
    0xC024: '・交信手順が”通信プロトコル”のコネクションにて，固定バッファ交信，またはランダムアクセス用バッファ交信を実施した。・交信手段が”固定バッファ(手順あり)”または，”固定バッファ(手順なし)”のコネクションにて，通信プロトコルによる交信を実施した。',
    0xC025: 'CONOPEN/OPEN命令または入出力信号によるオープン処理時に，使用用途設定エリアの指定に誤りがある。',
    0xC026: '通信プロトコル設定データの読出し/書込み/照合中に異常が発生した。',
    0xC027: 'ソケット通信の伝文送信に失敗した。',
    0xC028: '固定バッファの伝文送信に失敗した。',
    0xC029: '・コントロールデータの内容がおかしい。・オープン設定パラメータが未設定なのに，オープン設定パラメータでのオープンを指定した。',
    0xC035: 'レスポンス監視タイマ値以内に，相手機器の生存確認ができなかった。',
    0xC040: '・レスポンス監視タイマ値以内に，すべてのデータを受信できなかった。・データ長分のデータを受信できなかった。・TCP/IPレベルで分割された伝文の残りを，レスポンス監視タイマ値以内に受信できなかった。',
    0xC050: 'Ethernet搭載ユニットの交信データコードが”ASCII”に設定されている場合に，バイナリ変換できないASCIIコードのデータを受信した。',
    0xC051: '・SLMP伝文の，CPUユニットのワード単位でのデバイス読出し/書込み点数が許容範囲外である。・SLMP伝文の，ロングカウンタに対する書込み点数が2ワード単位でない。',
    0xC052: 'SLMP伝文の，CPUユニットのビット単位でのデバイス読出し/書込み点数が許容範囲外である。',
    0xC053: 'SLMP伝文の，CPUユニットのビット単位でのランダムデバイス読出し/書込み点数が許容範囲外である。',
    0xC054: 'SLMP伝文の，CPUユニットのワード・ダブルワード単位でのランダムデバイス読出し/書込み点数が許容範囲外である。',
    0xC055: 'SLMP伝文の，ファイルの読出し/書込みサイズが許容範囲外である。',
    0xC056: '最大アドレスを超える書込みおよび読出し要求である。',
    0xC057: 'SLMP伝文の要求データ長が，キャラクタ部(テキストの一部)のデータ数と合わない。',
    0xC058: 'SLMP伝文の，ASCII－バイナリ変換後の要求データ長が，キャラクタ部(テキストの一部)のデータ数と合わない。',
    0xC059: '・SLMP伝文のコマンド，サブコマンドの指定に誤りがある。・対象機器が未サポートの機能を実行した。',
    0xC05A: 'SLMP伝文で指定されたデバイスに対して，Ethernet搭載ユニットから読出し/書込みができない。',
    0xC05B: 'SLMP伝文で指定されたデバイスに対して，Ethernet搭載ユニットから読出し/書込みができない。',
    0xC05C: '・受信したSLMP伝文の要求データに誤りがある。・iQSS機能実行時の通信設定の設定値が範囲外である。・iQSS機能実行時，対象機器に設定できない通信設定項目を設定した。・iQSS機能実行時，対象機器で設定必須の項目が未設定である。',
    0xC05D: 'SLMP伝文”モニタ登録/解除”コマンドによるモニタ登録を行う前に，”モニタ要求”コマンドを受信した。',
    0xC05E: '・SLMP伝文をEthernet搭載ユニットが受信し，アクセス先から応答が返るまでの時間が，SLMPコマンドに設定された監視タイマの値を超えた。・応答伝文のないコマンドを指定したSLMPの要求伝文を，他ネットワークNo.のユニットをアクセス先として送信した。',
    0xC05F: 'SLMP伝文で指定されたアクセス先には，実行できない要求である。',
    0xC060: 'SLMP伝文の，ビットデバイスに対する要求内容に誤りがある。',
    0xC061: '・SLMP伝文の要求データ長が，キャラクタ部(テキストの一部)のデータ数と合わない。・ラベル書込みコマンドで指定した書込みデータの長さが偶数バイトでない。・iQSS機能実行時，異常なフレームを受信した。',
    0xC070: 'SLMP伝文で指定されたアクセス先は，デバイスメモリの拡張指定に対応していない。',
    0xC071: 'SLMP伝文のR/Q/QnACPU以外に対するデバイス読出し/書込み点数が範囲外である。',
    0xC072: 'SLMP伝文の要求内容に誤りがある。(ワードデバイスに対するビット単位の読出し/書込みなど)',
    0xC073: 'SLMP伝文のアクセス先がサポートしていない要求である。(R/Q/QnACPU以外に対するダブルワードアクセス点数の指定があるなど)',
    0xC075: 'ラベルアクセスにおける要求データ長が範囲外である。',
    0xC081: '再イニシャル実行に伴うEthernet搭載ユニットの終了処理が行われており，リンク専用命令交信の到達確認ができない。',
    0xC083: 'リンク専用命令交信で，交信処理が異常終了した。',
    0xC084: 'リンク専用命令交信で，交信処理が異常終了した。',
    0xC085: 'リンク専用命令SENDで指定した対象局格納チャンネルは，対象局にて現在使用中である。',
    0xC0B2: 'MELSOFT接続，リンク専用命令，SLMPの中継局/相手局で受信バッファに空きがない，または送信バッファに空きがない。(送信・受信バッファフルエラー)',
    0xC0B3: 'CPUユニットから処理できない要求があった。',
    0xC0B6: '専用命令で指定されたチャンネルが範囲外である。',
    0xC0BA: 'CONCLOSE/CLOSE命令によるクローズ処理中のため，送信要求を受け付けられない。',
    0xC0C4: '通信中にUINI命令が実行された。',
    0xC0D0: 'リンク専用命令のデータ長の指定に誤りがある。',
    0xC0D1: 'リンク専用命令の再送回数の指定に誤りがある。',
    0xC0D3: '他ネットワークとの交信の中継局数が，許容数を超えた。',
    0xC0D4: '他ネットワークとの交信の中継局数が，許容数を超えた。',
    0xC0D5: 'リンク専用命令のリトライ回数の指定に誤りがある。',
    0xC0D6: 'リンク専用命令のネットワークNo./局番の指定に誤りがある。',
    0xC0D7: 'イニシャル処理が完了していない状態で送信処理が行われた。',
    0xC0D8: '指定したブロック数が範囲を越えている。',
    0xC0D9: 'SLMP伝文のサブコマンドの指定に誤りがある。',
    0xC0DA: '交信タイムチェック時間以内に，PINGテストの応答を受信できなかった。',
    0xC0DB: 'PINGテストする対象先のIPアドレス/ホスト名に誤りがある。',
    0xC0DE: '指定された到達監視時間以内にデータを受信できなかった。',
    0xC101: 'DNSサーバから応答を受信できなかった。',
    0xC1A2: '・要求に対する応答を受信できなかった。・トランジェント伝送で，他のネットワークへの中継回数が7回を超えた。',
    0xC1A4: '・SLMP伝文のコマンド，サブコマンド，要求先ユニットI/O番号の指定に誤りがある。・ERRCLEAR命令で指定したクリア機能指定に誤りがある。・ERRRD命令で指定した読出し対象情報指定に誤りがある。・RJ71EN71のEthernetポートに直結接続してEthernet診断，CC-Link IEフィールドネットワーク診断またはCCLinkIEコントローラネットワーク診断を使用しようとした。・対象機器が未サポートの機能を実行した。',
    0xC1A5: '対象局またはクリア対象の指定に誤りがある。',
    0xC1A6: 'コネクションNo.の指定に誤りがある。',
    0xC1A7: 'ネットワークNo.の指定に誤りがある。',
    0xC1A8: '局番の指定に誤りがある。',
    0xC1A9: 'デバイスNo.の指定に誤りがある。',
    0xC1AA: 'デバイス名の指定に誤りがある。',
    0xC1AC: '再送回数の指定に誤りがある。',
    0xC1AD: 'データ長の指定に誤りがある。',
    0xC1AF: 'ポート番号の指定に誤りがある。',
    0xC1B0: '指定されたコネクションはすでにオープン処理が完了している。',
    0xC1B1: '指定されたコネクションはオープン処理が完了していない。',
    0xC1B2: 'CONOPEN/CONCLOSE/OPEN/CLOSE命令でオープン/クローズ処理を実行中のコネクションを指定して処理を行った。',
    0xC1B3: '指定されたチャンネルは他の送受信命令が実行中である。',
    0xC1B4: '到達時間の指定に誤りがある。',
    0xC1B8: 'データを受信していないチャンネルに対してRECV命令を実行した。',
    0xC1B9: '指定されたコネクションに対してCONOPEN/OPEN命令を実行できない。',
    0xC1BA: 'イニシャル未完了状態で専用命令を実行した。',
    0xC1BB: 'リンク専用命令の対象局CPU種別に誤りがある。',
    0xC1BC: 'リンク専用命令の対象ネットワークNo.に誤りがある。',
    0xC1BD: 'リンク専用命令の対象局番に誤りがある。',
    0xC1BE: '専用命令のコマンドコードに誤りがある。',
    0xC1BF: '専用命令の使用チャンネルに誤りがある。',
    0xC1C0: 'トランジェントデータに誤りがある。',
    0xC1C1: 'トランジェントデータに誤りがある。',
    0xC1C2: '専用命令で二重に受信した。',
    0xC1C4: 'リンク専用命令の到達確認が異常完了した。',
    0xC1C5: '対象局が未サポートの専用命令を実行した。',
    0xC1C6: '専用命令の実行・異常時完了タイプの設定に誤りがある。',
    0xC1C7: 'REQ命令のリクエストタイプの設定に誤りがある。',
    0xC1C8: '使用中のチャンネルを指定して専用命令を実行した。',
    0xC1C9: 'ZNRD/ZNWR命令のデバイス指定が誤っている。',
    0xC1CA: 'ZNRD/ZNWR命令のデバイス指定が誤っている。',
    0xC1CB: 'トランジェントデータに誤りがある。',
    0xC1CC: 'SLMPSND命令で許容範囲を超えるデータ長の応答を受信した。',
    0xC1CD: 'SLMPSND命令の伝文送信に失敗した。',
    0xC1D0: '専用命令の要求先ユニットI/O番号に誤りがある。',
    0xC1D2: 'リンク専用命令の対象局IPアドレスの設定に誤りがある。',
    0xC1D3: 'コネクションの交信手段に対応していない専用命令を実行した。',
    0xC200: 'リモートパスワードに誤りがある',
    0xC201: '交信に使ったポートがリモートパスワードのロック状態である。',
    0xC202: '他局アクセスを行ったときに，リモートパスワードのアンロック処理ができなかった。',
    0xC203: 'リモートパスワードのチェックで異常が発生した。',
    0xC204: 'リモートパスワードのアンロック処理を要求した機器と異なる。',
    0xC205: '他局アクセスを行ったときに，リモートパスワードのアンロック処理ができなかった。',
    0xC207: 'ファイル名の文字数が長すぎる。',
    0xC208: 'パスワード長が範囲外である。',
    0xC400: '通信プロトコル準備未完了時にECPRTCL命令を実行した。',
    0xC401: 'ECPRTCL命令で指定したプロトコル番号が，Ethernet搭載ユニットの登録されていない。',
    0xC402: 'Ethernet搭載ユニットに登録したプロトコル設定データに異常があり，ECPRTCL命令が実行できない。',
    0xC403: '専用命令が同時に実行された。',
    0xC404: 'ECPRTCL命令で実行中のプロトコルがキャンセルされた。',
    0xC405: 'ECPRTCL命令で指定したプロトコル番号に誤りがある。',
    0xC406: 'ECPRTCL命令のプロトコル連続実行数に誤りがある。',
    0xC407: 'ECPRTCL命令で指定したコネクションNo.に誤りがある。',
    0xC408: 'ECPRTCL命令の通信プロトコルの送信処理に異常が発生した。',
    0xC410: 'ECPRTCL命令の受信待ち時間がタイムアウトした。',
    0xC412: 'ASCII-バイナリ変換できないデータを受信した。',
    0xC413: '通信プロトコルで受信したデータの桁数が不足している。',
    0xC414: '通信プロトコルで受信したデータの桁数に誤りがある。',
    0xC417: '通信プロトコルで受信したデータのデータ長，またはデータ数が範囲外。',
    0xC420: 'プロトコル設定データの書込みに失敗した。',
    0xC421: 'フラッシュROM書込み回数がオーバーしているユニットに対して書込みを要求した。',
    0xC430: 'ECPRTCL命令実行中にプロトコル設定データの書込みが行われた。',
    0xC431: 'ECPRTCL命令実行中にコネクションのクローズ処理が行われた。',
    0xC440: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC441: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC442: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC443: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC444: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC445: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC446: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC447: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC448: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC449: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44A: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44B: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44C: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44D: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44E: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC44F: 'Ethernet診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xC610: 'ユニットの処理が異常完了した。',
    0xC611: 'ユニットの処理が異常完了した。',
    0xC612: 'ユニットの処理が異常完了した。',
    0xC613: 'ユニットの処理が異常完了した。',
    0xC614: 'ユニットの処理が異常完了した。',
    0xC615: 'ユニットの処理が異常完了した。',
    0xC616: 'FTPサーバへの制御ポートの接続に失敗した。',
    0xC617: 'FTPサーバへの制御ポートの切断に失敗した。',
    0xC618: 'FTPサーバへのログインに失敗した。',
    0xC619: 'FTPサーバへのFTPコマンドの実行に失敗した。',
    0xC620: 'FTPサーバへのデータ転送ポートの接続に失敗した。',
    0xC621: 'FTPサーバへのデータ転送ポートの切断に失敗した。',
    0xC622: 'ファイル転送中にエラーが発生した。',
    0xC623: 'FTPサーバから応答を受信できなかった。',
    0xC700: 'ユニットの処理が異常完了した。',
    0xC701: 'IPパケット中継機能による交信にて，IPアドレス(ネットワークNo.)の設定が誤っている。',
    0xC702: 'IPパケット中継機能による交信にて，IPアドレス(局番)の設定が誤っている。',
    0xC703: 'IPパケット中継機能による交信にて，宛先IPアドレス(上位)が誤っている。',
    0xC704: 'IPパケット中継機能による交信にて，宛先IPアドレス(下位)が誤っている。',
    0xC705: 'ユニットの処理が異常完了した。',
    0xC706: 'ユニットの処理が異常完了した。',
    0xC707: 'ユニットの処理が異常完了した。',
    0xC708: 'IPパケット中継機能による交信にて，Ethernet機器と接続しているEthernet搭載ユニットの”応用設定”の”IPパケット中継設定”で”IPパケット中継機能使用有無”が”使用しない”になっている',
    0xC709: 'MELSOFT直結接続で交信異常が発生した。',
    0xC810: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。正しいパスワードを設定して再度実行してください。',
    0xC811: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。1分後に正しいパスワードを設定して再度実行してください。',
    0xC812: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。5分後に正しいパスワードを設定して再度実行してください。',
    0xC813: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。15分後に正しいパスワードを設定して再度実行してください。',
    0xC814: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。60分後に正しいパスワードを設定して再度実行してください。',
    0xC815: 'リモートパスワード認証が必要なアクセス時に，リモートパスワードのパスワード認証に失敗した。60分後に正しいパスワードを設定して再度実行してください。',
    0xC816: 'セキュリティ機能が動作し，リモートパスワード認証不可状態である。',
    0xC840: 'トランジェントの要求数が，配送処理で同時処理可能な上限を超過した。',
    0xC842: '宛先ネットワークNo.へ到達するためのルーチング設定がされていない。',
    0xC843: '設定されているネットワーク種別では実行できないリンク専用命令を実行した。',
    0xC844: '異常なフレームを受信した。・未対応変換前プロトコル・未対応フレームタイプ・アプリケーションヘッダ可変部・アプリケーションヘッダHDS・アプリケーションヘッダRTP・応答不要の読出し系コマンド',
    0xC860: 'MODBUS/TCPによる交信で，CPU応答監視タイマがタイムアウトした。',
    0xC861: 'MODBUS/TCPによる交信で，サポートしていないファンクションコードの要求伝文を受信した。',
    0xC862: 'MODBUS/TCPによる交信で，サポートしていないサブコードの要求伝文を受信した。',
    0xC863: 'MODBUS/TCPによる交信で，受信した要求伝文で指定されたMODBUSデバイスに対して，MODBUSデバイス割付パラメータが設定されていない。',
    0xC864: 'MODBUS/TCPによる交信で，受信した要求伝文で指定されたMODBUSデバイスの範囲が，MODBUSデバイス割付パラメータの設定範囲を超えている。',
    0xC865: 'MODBUS/TCPによる交信で，受信した要求伝文で指定されたMODBUSデバイスの範囲が，MODBUSデバイスの上限を超えている。(拡張ファイルレジスタの上限は10000，MODBUSデバイスは65536です。)',
    0xC866: 'MODBUS/TCPによる交信で，受信した要求伝文で指定されたMODBUSデバイスの先頭アドレス，アクセス点数が異常である。',
    0xC867: 'MODBUS/TCPによる交信で，受信した要求伝文の書込み点数指定とバイト数指定が合っていない。',
    0xC868: 'MODBUS/TCPによる交信で，受信した書込みデータサイズと，バイト数指定が合っていない。',
    0xC869: 'MODBUS/TCPによる交信で，受信した要求伝文(FC20，FC21)で指定されたリファレンスタイプの値が異常である。',
    0xC86A: 'MODBUS/TCPによる交信で，受信した要求伝文のデータ部の内容が異常である。受信した要求伝文のサイズが，該当ファンクションコードに必要な最低サイズより小さい，または最大サイズより大きい。',
    0xC86B: 'MODBUS/TCPによる交信で，受信した要求伝文のMBAPヘッダの内容が異常である。',
    0xC86C: '同時受信可能要求伝文数を越える要求伝文を受信した。',
    0xCEE0: '接続機器の自動検出中に，他の周辺機器から検出，または他のiQSS機能を実行した。',
    0xCEE1: '異常なフレームを受信した。',
    0xCEE2: '異常なフレームを受信した。',
    0xCF10: '異常なフレームを受信した。',
    0xCF20: '・通信設定の設定値が範囲外である。・対象機器に設定できない通信設定項目を設定した。・対象機器で設定必須の項目が未設定である。',
    0xCF30: '対象機器がサポートしていないパラメータを指定した。',
    0xCF31: '異常なフレームを受信した。',
    0xCF70: 'Ethernetの通信経路で異常が発生した。',
    0xCF71: 'タイムアウトエラーが発生した。',
    0xCF80: 'シンプル機器通信で，交信相手と接続できない。または切断された。',
    0xCF81: 'シンプル機器通信で，通信タイムアウトにより送受信に失敗した。',
    0xCF82: 'シンプル機器通信で，送信パケットに設定した”変換なし変数(可変長)”または”データ数可変”の”変換あり変数(可変長)”において，”送受信データ長格納エリア”または”送受信データ数格納エリア”の値が設定可能な範囲を超えている。',
    0xCF83: 'シンプル機器通信で，送信データのデータサイズが0になっている。',
    0xCF84: 'シンプル機器通信で，送信パケットの送信に失敗した。',
    0xCF85: 'シンプル機器通信で，範囲外のデータを設定した。',
    0xCF8A: 'シンプル機器通信で，CPUユニットに対する要求に失敗した。',
    0xCF8C: 'シンプル機器通信で，受信データがパラメータで設定した全受信パケットと照合一致しなかった。',
    0xCFB0: 'シンプルCPU通信で，再送タイムアウトにより送信に失敗した。',
    0xCFB1: 'シンプルCPU通信で，交信相手と接続できない。または切断された。',
    0xCFB2: 'シンプルCPU通信で，指定された自局ポート番号は重複して使用されている。',
    0xCFB3: 'シンプルCPU通信で，CPUユニットに対する要求に失敗した。',
    0xCFB4: 'シンプルCPU通信で，相手機器から異常応答を受信した。',
    0xCFB5: 'シンプルCPU通信で，相手機器から受信したフレームが異常である。',
    0xCFBD: 'シンプルCPU通信で，交信相手側に指定したデバイスが仕様の範囲外である。',
    0xCFBE: 'シンプルCPU通信診断実行時にエンジニアリングツールとの交信異常が発生した。',
    0xCFBF: 'シンプルCPU通信を実行できない。',
}

_REMOTE_PASSWORD_END_CODES = {0xC200, 0xC201, 0xC202, 0xC203, 0xC204, 0xC205, 0xC810, 0xC811, 0xC812, 0xC813, 0xC814, 0xC815, 0xC816}


def get_end_code_name(end_code: int) -> str:
    """Return a compact code-derived diagnostic label for an SLMP end code.

    Use numeric codes or category helpers for branching.
    """
    return _END_CODE_NAMES.get(end_code, "unknown_plc_end_code")


def get_end_code_message(end_code: int, language: SlmpEndCodeLanguage = "en") -> str | None:
    """Return the error detail/cause message for an SLMP end code.

    Remote-password retry-delay codes include the wait time because the
    detail text alone is identical.
    """
    table = _END_CODE_MESSAGES_JA if language == "ja" else _END_CODE_MESSAGES_EN
    return table.get(end_code)


def is_remote_password_end_code(end_code: int) -> bool:
    """Return True if the SLMP end code is related to remote password protection."""
    return end_code in _REMOTE_PASSWORD_END_CODES
